dist: trusty
sudo: false

language: scala
services:
  - docker

scala:
   - 2.11.11

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2

before_script:
 - docker run -d -p 9432:9432 --name bblfsh bblfsh/server
 - ./local-install-bblfsh-client-scala.sh
 

script:
 - ./sbt ++$TRAVIS_SCALA_VERSION test
 - ./test