dist: trusty
sudo: false

language: scala
services:
  - docker

jdk:
  - openjdk8

scala:
   - 2.11

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt

install:
 - go get -v github.com/Masterminds/glide
 - cd $GOPATH/src/github.com/Masterminds/glide && git checkout tags/0.10.2 && go install && cd -
 - mkdir -p $GOPATH/src/github.com/src-d && ln -s $PWD $GOPATH/src/github.com/src-d/berserker

before_script:
 - docker run -d -p 9432:9432 --name bblfsh bblfsh/server
 - ./local-install-bblfsh-client-scala.sh

script:
 - pwd; find -L $GOPATH/src/github.com/src-d/
 - cd $GOPATH/src/github.com/src-d/berserker/enrysrv && ./build && cd - || travis_terminate 1
 - enrysrv/bin/enrysrv server&
 - ./sbt ++$TRAVIS_SCALA_VERSION test || travis_terminate 1
 - ./test